spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:/data/wallet
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate.ddl-auto: create-drop
